version: "3.9"
services:
  postgres:
    container_name: domainator_postgres
    image: postgres:16
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  redis:
    container_name: domainator_redis
    image: redis:7
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "200mb", "--maxmemory-policy", "volatile-ttl"]
    ports:
      - "6379:6379"
