version: "3.9"
services:
  postgres:
    container_name: domainator_postgres
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  redis:
    container_name: domainator_redis
    image: redis:7
    ports:
      - "6379:6379"
