version: '3.1'

services:
  db_test:
    container_name: domainator_test_pg
    image: postgres:15-alpine
    restart: on-failure
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "postgres"]
      interval: 15s
      timeout: 10s
      retries: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: domainatortest
    ports:
      - 54340:5432
